spring:
  application:
    name: restaurant-reservation-api
#  datasource:
#    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:restaurant-reservation-api}
#    username: ${DATABASE_USERNAME:postgres}
#    password: ${DATABASE_PASSWORD:postgres}
#
#    jpa:
#      show-sql: true
#      hibernate:
#        ddl-auto: update
#
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL95Dialect
#    dbcp2:
#      test-while-idle: true
#      validation-query: SELECT 1
#      driver-class-name: org.postgresql.Driver

server:
  error:
    include-stacktrace: never

