name: CI Pipeline with Dockerfile

on:
  push:
    branches:
      - master  # Build automático ao enviar código para a branch "master"
  workflow_dispatch:  # Deploy manual

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Step 1: Checkout o código
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Configurar o JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      # Step 3: Build com Gradle usando o JDK 21
      - name: Build with Gradle
        run: make build

      # Step 4: Run tests with Gradle
      - name: Run unit tests with Gradle
        run: make unitTest

      #Step 5: Run integration tests with Gradle
      - name: Run integration tests with Gradle
        run: make integrationTest

      # Step 6: Run system tests with Gradle
      - name: Run system tests with Gradle
        run: make systemTest

      # Step 7: Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 8: Login no Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 9: Build multi-architecture Docker image
      - name: Build and push Docker image (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest
          platforms: linux/amd64,linux/arm64
